export const dataArr = [
    {
        "id": 463,
        "name": "Абраамян А.М. (вывеска Парикмахерская Дом Быта)",
        "address": "192012, Санкт-Петербург г, вн.тер.г. Обуховский, ул Ново-Александровская, 14",
        "tel": "9041214",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 464,
        "name": "Абросимова Елена",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 17, к. 2, кв. 20",
        "tel": "79119747495",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 465,
        "name": "Абунагимова Ирина",
        "address": "193149, Ленинградская обл, м.р-н Всеволожский, г.п. Свердловское, д Новосаратовка, наб Октябрьская, 118",
        "tel": "89112417945",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 466,
        "name": "Агасарян М.Р. (вывеска Хозяюшка)",
        "address": "192148, Санкт-Петербург г, ул Седова, 29",
        "tel": "89062619714",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 467,
        "name": "Агос (Караваевская 28, вывеска Фэмили) ГОЛОВНОЙ",
        "address": "192177, Санкт-Петербург г, вн.тер.г. Рыбацкое, ул Караваевская, 28",
        "tel": "+79219802376",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 468,
        "name": "Адлер Анна",
        "address": "190005, Санкт-Петербург г, Советский пр-кт, д. 2,парадная 4, кв. 267, этаж 1, второй дом у дороги",
        "tel": "89052236596",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 469,
        "name": "Акиншина Ксения",
        "address": "192171, Город Санкт-Петербург, вн.тер.г. муниципальный округ Ивановский, ул Фарфоровская, д. 14, литера П, кв. 3",
        "tel": "+79111651200",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 470,
        "name": "Акцент (Дальневосточный)",
        "address": "193079, Санкт-Петербург г, пр-кт Дальневосточный, д. 69, к. 6, кв. 77",
        "tel": "+79626833330",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 471,
        "name": "Алтухова М.В.",
        "address": "192029, Санкт-Петербург г, вн.тер.г. Невская застава, пр-кт Елизарова, 6",
        "tel": "+78129255167",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 472,
        "name": "Ангел (Металлострой)",
        "address": "196641, Санкт-Петербург г, вн.тер.г. поселок Металлострой, п Металлострой, ул Плановая, 6",
        "tel": "+79219267873",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 473,
        "name": "Ария",
        "address": "192029, Санкт-Петербург г, пр-кт Елизарова, д. 14, литера А",
        "tel": "+79219933531",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 474,
        "name": "Атаян Т.В. (вывеска Констант) ОПТ",
        "address": "192029, Санкт-Петербург г, Бабушкина ул, дом № 14",
        "tel": "79119212204",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 475,
        "name": "Атоян Арман Арманович",
        "address": "193149, Санкт-Петербург г, наб Октябрьская, д. 122, к. 3",
        "tel": "89216407379",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 476,
        "name": "Баня (Парикмахерская)",
        "address": "196641, Санкт-Петербург г, вн.тер.г. поселок Металлострой, п Металлострой, ул Пионерская, 7",
        "tel": "+79967921298",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 477,
        "name": "Баранова Наталья (Металлострой)",
        "address": "196641, Санкт-Петербург г, п Металлострой, ул Садовая, д. 8",
        "tel": "89213249511",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 478,
        "name": "Барбер Генко (Шлиссельбургский)",
        "address": "192076, Санкт-Петербург г, пр-кт Шлиссельбургский, д. 12, к. 1, литера А",
        "tel": "89117153188",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 479,
        "name": "Белая Маргарита",
        "address": "192177, Санкт-Петербург г, ул Караваевская, д. 401, кв. 30",
        "tel": "89119141023",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 480,
        "name": "Белова Ирина (вывеска Бьюти Белка)",
        "address": "193079, Город Санкт-Петербург, вн.тер.г. муниципальный округ Народный, пр-кт Дальневосточный, д. 69, к. 5, литера А",
        "tel": "+79217897841",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 481,
        "name": "Бережная Полина",
        "address": "192012, Город Санкт-Петербург, пр-кт Обуховской Обороны, д. 227, к. 2, литера А, кв. 51",
        "tel": "+79161000120",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 482,
        "name": "Би Бьюти Дина (Русановская)",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 19, к. 1, литера А",
        "tel": "+79516766558",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 483,
        "name": "Бирюлина Светлана Александровна (Илерия, вывеска Облако) ОПТ",
        "address": "192131, Санкт-Петербург г, вн.тер.г. Ивановский, ул Ивановская, д. 20",
        "tel": "+79117457567",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 484,
        "name": "Большакова Елена (вывеска Орхидея)",
        "address": "192029, Санкт-Петербург г, ул Ткачей, д. 68, к. 2",
        "tel": "+79215509220",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 485,
        "name": "Бьюти Бар Нест ГОЛОВНОЙ",
        "address": "193149, Санкт-Петербург г, вн.тер.г. Народный, ул Русановская, 18",
        "tel": "89112209960",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 486,
        "name": "Бьюти Дрим Русановская (Ксения Жидаева)",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 16, к. 1, кв. 451",
        "tel": "+79312122347",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 487,
        "name": "Бьюти Студия (Металлострой)",
        "address": "196641, Санкт-Петербург г, вн.тер.г. поселок Металлострой, п Металлострой, ул Полевая, 18",
        "tel": "+79216549913",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 488,
        "name": "Валигура Юлия (Обуховской Обороны)",
        "address": "192012, Санкт-Петербург г, пр-кт Обуховской Обороны, д. 110, к. 1 литера А, кв. 1239",
        "tel": "+79818155342",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 489,
        "name": "Васильев Д.А. (вывеска София)",
        "address": "192171, Санкт-Петербург г, вн.тер.г. Ивановский, ул Ивановская, 15",
        "tel": "79217974518",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 490,
        "name": "Васильева Е.А. (вывеска Селена)",
        "address": "192076, Санкт-Петербург г, вн.тер.г. Рыбацкое, ул Прибрежная, 4",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 491,
        "name": "Великанова Анастасия",
        "address": "192171, Санкт-Петербург г, вн.тер.г. муниципальный округ Ивановский, ул Полярников, д. 17, литера А, кв. 22",
        "tel": "+79111233159",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 492,
        "name": "Власова Елена",
        "address": "192077, Город Санкт-Петербург, тер. Усть-Славянка, ул Заводская, д. 15, стр. 1, кв. 389",
        "tel": "89112003870",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 493,
        "name": "Гамма (Шлиссельбургский)",
        "address": "192177, Санкт-Петербург г, пр-кт Шлиссельбургский, д. 17, к. 1, литера Б",
        "tel": "79219410040",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 494,
        "name": "Гемма (Бабушкина 52)",
        "address": "192131, Санкт-Петербург г, ул Бабушкина, д. 52",
        "tel": "+79216575557",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 495,
        "name": "Глянец (Металлострой)",
        "address": "196641, Санкт-Петербург г, п Металлострой, ул Полевая, д. 12, ТЦ Колибри",
        "tel": "+79817410451",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 496,
        "name": "Грация (Седова)",
        "address": "192148, Санкт-Петербург г, ул Седова, д. 42, к. 2, литера А",
        "tel": "+79313161130",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 497,
        "name": "Гусева Е.Б (Фри Стайл) ОПТ",
        "address": "192171, Санкт-Петербург г, вн.тер.г. Ивановский, ул Ивановская, 13",
        "tel": "+79817581422",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 498,
        "name": "Давоян Мери",
        "address": "192171, Санкт-Петербург г, ул Седова, д. 60, литера А, кв. 118",
        "tel": "+79627073226",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 499,
        "name": "Давудян Гаяне",
        "address": "192171, Санкт-Петербург г, ул Бабушкина, д. 36, кв. 90",
        "tel": "+79643206995",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 500,
        "name": "Дельфин (Шлиссельбургский 14)",
        "address": "192076, Санкт-Петербург г, пр-кт Шлиссельбургский, д. 14, к. 1, литера А",
        "tel": "79119094207",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 501,
        "name": "Дерюгина Наталья Владимировна",
        "address": "192012, Санкт-Петербург г, вн.тер.г. муниципальный округ Обуховский, пр-кт Обуховской Обороны, д. 217, кв. 18",
        "tel": "89819722546",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 502,
        "name": "Дуэт (Металлострой)",
        "address": "Санкт-Петербург г, д. 10, вн.тер.г. поселок Металлострой, ул Центральная",
        "tel": "+78129847882",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 503,
        "name": "Ева (Бабушкина 14)",
        "address": "192029, Санкт-Петербург г, ул Бабушкина, 14",
        "tel": "+79643226343",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 504,
        "name": "Евсюнина Людмила",
        "address": "192177, Санкт-Петербург г, ул Караваевская, д. 28, к. 1, кв. 651",
        "tel": "89522135526",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 505,
        "name": "Епишева Альмира (салон Селект, Русановская)",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 19, к. 3, литера А, кв. 294, парадная 3",
        "tel": "89117271032",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 506,
        "name": "Ермолаева Галина ЧМ",
        "address": "192148, Санкт-Петербург г, ул Крупской, д. 24, к. 2, литера А, кв. 6",
        "tel": "+79531625415",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 507,
        "name": "Зажирская Т.В. (вывеска Бьюти студия)ОТЗВОН ЗА ЧАС",
        "address": "193149, Город Санкт-Петербург, ул Русановская, д. 17, к. 3, литера А, кв. 4",
        "tel": "+79817648481",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 508,
        "name": "Зайцева Анна (Русановская)",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 18, к. 6, стр. 1, кв. 191",
        "tel": "+79817346643",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 509,
        "name": "Закирова Махаббат (ЧМ  Мария, Подружка)",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 18, к. 6, кв. 504, этаж 11, 2 парадная с улицы",
        "tel": "+79697029494",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 510,
        "name": "Заманова Назиля",
        "address": "192174, Санкт-Петербург г, ул Седова, 142",
        "tel": "89119777964",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 511,
        "name": "Заманова Назиля (Бабушкина)",
        "address": "192131, Санкт-Петербург г, б-р Красных Зорь, д. 1, литера А",
        "tel": "+79633453012",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 512,
        "name": "Золушка (Понтонный,Заводская 35)",
        "address": "190000, Санкт-Петербург г, вн.тер.г. поселок Понтонный, п Понтонный, ул Заводская, д. 35",
        "tel": "+79119556723",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 513,
        "name": "Иванов В.В. (Русановская, вывеска Селект)",
        "address": "193149, Санкт-Петербург г, вн.тер.г. Народный, ул Русановская, 19",
        "tel": "+79819151540",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 514,
        "name": "Иванова Анна Михайловна ИП",
        "address": "192076, Санкт-Петербург г, вн.тер.г. Рыбацкое, пр-кт Рыбацкий, 39",
        "tel": "+79110233343",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 515,
        "name": "Иванова Екатерина (Русановская)",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 18, к. 6, стр. 1, кв. 497",
        "tel": "+79110817270",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 516,
        "name": "Иванова Наталья (Шлиссельбургский)",
        "address": "192177, Санкт-Петербург г, пр-кт Шлиссельбургский, д. 45, литера А, кв. 279",
        "tel": "+79531708921",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 517,
        "name": "Изюм",
        "address": "192029, Санкт-Петербург г, ул Бабушкина, д. 29, к. 1",
        "tel": "+79626951140",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 518,
        "name": "Иманова (Бабушкина)",
        "address": "192029, Санкт-Петербург г, ул Бабушкина, 11",
        "tel": "+79818616165",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 519,
        "name": "Иманова (Народная 39)",
        "address": "193315, Санкт-Петербург г, Народная ул, дом № 39",
        "tel": "89219543473",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 520,
        "name": "Истратова Марина (Плаза) ОПТ",
        "address": "192171, Санкт-Петербург г, ул Ивановская, д. 7, литера А",
        "tel": "+79522424624",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 521,
        "name": "Казиев Булат",
        "address": "190000, Санкт-Петербург г, Обуховской обороны пр-кт, дом № 86 лит.Н",
        "tel": "+79219561182",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 522,
        "name": "Кайсарова (вывеска Арман)",
        "address": "г Санкт-Петербург, ул Народная, дом 55, литера Т",
        "tel": "+79995255611",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 523,
        "name": "Калашникова Ольга",
        "address": "192076, Санкт-Петербург г, пр-кт Обуховской обороны, д. 138, к. 2, кв. 390",
        "tel": "+79507960642",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 524,
        "name": "Карпова Ольга",
        "address": "190000, Санкт-Петербург г, Елизарова пр-кт, дом 1,со двора,на двери 48А",
        "tel": "+79522323723",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 525,
        "name": "Каткова (Металлострой, вывеска Модерн) ОПТ",
        "address": "Санкт-Петербург г, вн.тер.г. поселок Металлострой, п Металлострой, ул Садовая, д. 21, к. 1, ЛИТ А",
        "tel": "88124646235",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 526,
        "name": "Кислякова А.В. (Блеск)",
        "address": "192012, Санкт-Петербург г, вн.тер.г. Обуховский, д. 209",
        "tel": "+79043339077",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 527,
        "name": "Ковалева Наталья (Парикмахерская Бабушкина 82/3)",
        "address": "192012, Санкт-Петербург г, ул Бабушкина, д. 82, к. 3, стр. 1, помещ. 18Н, вывеска Парикмахерская",
        "tel": "+79213770017",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 528,
        "name": "Коваленко О.Н. (Металлострой)",
        "address": "196641, Санкт-Петербург г, п Металлострой, ул Садовая, д. 12, литера А, кв. 39",
        "tel": "+79117279188",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 529,
        "name": "Комаров (Народная)",
        "address": "193079, Город Санкт-Петербург, вн.тер.г. муниципальный округ Народный, ул Народная, д. 1, литера Б",
        "tel": "+79252864343",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 530,
        "name": "Кононова (вывеска Парикмахерская Для всей семьи)",
        "address": "193149, Санкт-Петербург г, наб Октябрьская, д. 118, к. 3, литера А",
        "tel": "89110328907",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 531,
        "name": "Королева А.Г. (вывеска Василиса) ОПТ",
        "address": "192029, Санкт-Петербург г, пр-кт Елизарова, д. 11, литера А",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 532,
        "name": "Кошкарева Нелли",
        "address": "192019, Санкт-Петербург г, ул Седова, д. 11, литера А, помещ. 217",
        "tel": "+79817710202",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 533,
        "name": "Кристалл (Рыбацкий пр)",
        "address": "Санкт-Петербург г, пр. Советский, д. 36, к. 2, кв. 1206",
        "tel": "+79046076555",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 534,
        "name": "Кротова Людмила Вениаминовна",
        "address": "196643, Санкт-Петербург г, п Понтонный, ул Южная, д. 35",
        "tel": "+79111549918",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 535,
        "name": "Кузьменко А.А. (об. обороны) ОПТ ГОЛОВНОЙ",
        "address": "192012, Санкт-Петербург г, Обуховской обороны пр-кт, дом № 243",
        "tel": "+79117271664",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 536,
        "name": "Кузьменко А.А. (Шлиссельбургский)",
        "address": "192177, Санкт-Петербург г, вн.тер.г. Рыбацкое, пр-кт Шлиссельбургский, 11",
        "tel": "88127005845",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 537,
        "name": "Кузьмина Ольга",
        "address": "196643, Санкт-Петербург г, п Саперный, пер Садовый, д. 5, литера А",
        "tel": "+79052702897",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 538,
        "name": "Курганская Ирина",
        "address": "192076, Санкт-Петербург г, вн.тер.г. муниципальный округ Рыбацкое, тер. Усть-Славянка, пр-кт Советский, д. 39, к. 1, кв. 173",
        "tel": "+79319709212",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 539,
        "name": "Кутузова О.Н.(Кузменко О.Н.)",
        "address": "193079, Санкт-Петербург г, наб Октябрьская, д. 68, литера А",
        "tel": "+79119140025",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 540,
        "name": "Лазер-Профи (салон Бьюти Дэй) ОПТ",
        "address": "192012, Санкт-Петербург г, пр-кт Обуховской Обороны, д. 110",
        "tel": "+79110850425",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 541,
        "name": "Лапина Ирина (Понтонный)",
        "address": "190000, Санкт-Петербург г, 2 п.Понтонный, Заводская, дом №",
        "tel": "89818490058",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 542,
        "name": "Леди (Ивановская 17)",
        "address": "192171, Санкт-Петербург г, ул Ивановская, д. 17, литера А",
        "tel": "+79219460035",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 543,
        "name": "Леруа (Обуховской Обороны)",
        "address": "192012, Санкт-Петербург г, пр-кт Обуховской Обороны, д. 116/1",
        "tel": "+79117165643",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 544,
        "name": "Лиана (Ткачей)",
        "address": "192029, Город Санкт-Петербург, вн.тер.г. муниципальный округ Невская застава, ул Ткачей, д. 68, к. 2, литера А",
        "tel": "+79657775525",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 545,
        "name": "Литвинова Ульяна (Демонстрация)",
        "address": "190000, Санкт-Петербург г, Невский рн, сектор 6",
        "tel": "+79817310217",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 546,
        "name": "Литвинова Ульяна (Новый клиент)",
        "address": "190000, Санкт-Петербург г, Невский район, сектор 6",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 547,
        "name": "ЛСтаил",
        "address": "190000, Санкт-Петербург г, Шлиссельбургский пр-кт, дом 24",
        "tel": "89217422460",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 548,
        "name": "Луна (Обуховской обороны)",
        "address": "192012, Санкт-Петербург г, пр-кт Обуховской Обороны, д. 251, литера А",
        "tel": "+79062569624",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 549,
        "name": "Макарова Елена (вывеска Бьюти) ОТЗВОН ЗА ЧАС",
        "address": "193079, Город Санкт-Петербург, наб Октябрьская, д. 104, к. 5, литера А, этаж 7, офис 708",
        "tel": "+79818211691",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 550,
        "name": "Макаровский (Бабушкина, вывеска Нота Бене)",
        "address": "192029, Санкт-Петербург г, Бабушкина ул, дом № 11",
        "tel": "4120939",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 551,
        "name": "Макаровский (Ивановская 13, вывеска Нота Бене)",
        "address": "192171, Санкт-Петербург г, вн.тер.г. Ивановский, ул Ивановская, 13",
        "tel": "89213326483",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 552,
        "name": "Макаровский В.Л. (Nota Bene Бабушкина 42)",
        "address": "192171, Санкт-Петербург г, ул Бабушкина, д. 42, к. 1, литера А",
        "tel": "+79522723822",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 553,
        "name": "Мечта (Ткачей)",
        "address": "192029, Санкт-Петербург г, ул Ткачей, д. 6, литера А",
        "tel": "+79046494242",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 554,
        "name": "Мильченко (Металлострой) ОПТ",
        "address": "Ленинградская обл, Металлострой п, Школьная ул, дом № 14 А",
        "tel": "4646818",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 555,
        "name": "Мир",
        "address": "190000, Санкт-Петербург г, ул Седова, д. 12 пом.117",
        "tel": "+79219945122",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 556,
        "name": "Миро Дива (Бабушкина 84)",
        "address": "192012, Санкт-Петербург г, вн.тер.г. муниципальный округ Обуховский, ул Бабушкина, д. 84, к. 2",
        "tel": "+79112349998",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 557,
        "name": "Мищенко Алла Валерьевна(Русановская19/1)",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 19, к. 1, литера А, кв. 232",
        "tel": "89626927052",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 558,
        "name": "Мулен Руж (Шелгунова)",
        "address": "192174, Санкт-Петербург г, вн.тер.г. Обуховский, ул Шелгунова, 9",
        "tel": "+79219571255",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 559,
        "name": "На Неве",
        "address": "192076, Санкт-Петербург г, вн.тер.г. Рыбацкое, пр-кт Рыбацкий, 18",
        "tel": "89110264745",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 560,
        "name": "Наша парикмахерская",
        "address": "192171, Санкт-Петербург г, вн.тер.г. муниципальный округ Ивановский, ул Бабушкина, д. 42, к. 1, литера А",
        "tel": "+79313524661",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 561,
        "name": "Незабудка ( Металлострой )",
        "address": "196641, Санкт-Петербург г, вн.тер.г. поселок Металлострой, п Металлострой, ул Центральная, д. 10, литера А",
        "tel": "+79219693634",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 562,
        "name": "Неоми (Русановская )",
        "address": "193149, Город Санкт-Петербург, вн.тер.г. муниципальный округ Народный, ул Русановская, д. 18, к. 3, стр. 1",
        "tel": "+79522375717",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 563,
        "name": "Ника (Седова 126) ОПТ",
        "address": "192174, Санкт-Петербург г, ул Седова, 126",
        "tel": "+79522283286",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 564,
        "name": "НКАтери",
        "address": "193149, Санкт-Петербург г, вн.тер.г. муниципальный округ Народный, ул Русановская, д. 13, к. 1, стр. 1",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 565,
        "name": "Нур ООО ОПТ",
        "address": "192171, Санкт-Петербург г, пер Матюшенко, д. 10",
        "tel": "+79119128862",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 566,
        "name": "Оводова Ирина",
        "address": "190000, Санкт-Петербург г, Советский пр-т, дом 36, корпус 2, кв.426",
        "tel": "+79522796169",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 567,
        "name": "Олери (Солви) ОПТ",
        "address": "192148, Санкт-Петербург г, вн.тер.г. муниципальный округ Невская застава, ул Седова, д. 30, литера А, кв. 35",
        "tel": "+79218801169",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 568,
        "name": "Орхидея (Понтонный)",
        "address": "196643, Санкт-Петербург г, п Понтонный, ул Южная, д. 33, литера А",
        "tel": "+79818490058",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 569,
        "name": "Павличенко Анастасия Леонидовна (Советский)",
        "address": "192076, Санкт-Петербург г, тер. Усть-Славянка, пр-кт Советский, д. 34, к. 2, кв. 484",
        "tel": "+79118158810",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 570,
        "name": "Панизник И.И. (Пляж) ОПТ",
        "address": "192174, Город Санкт-Петербург, ул Седова, д. 87, к. 9, литера А, этаж 2",
        "tel": "+79516879347",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 571,
        "name": "Пиман Юлия(ЧМ)",
        "address": "192177, Санкт-Петербург г, ул Дмитрия Устинова, д. 8, кв. 258",
        "tel": "89213446645",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 572,
        "name": "Плугарь Ольга (Парикмахерская для всей семьи)",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 19, к. 4, литера А",
        "tel": "+79516682164",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 573,
        "name": "Подружка (Седова 88)",
        "address": "Санкт-Петербург г, Седова ул, дом 88, литер Б",
        "tel": "+79522701771",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 574,
        "name": "Попик Лилия",
        "address": "192077, Город Санкт-Петербург, тер. Усть-Славянка, пр-кт Советский, д. 36, к. 2, стр. 1, кв. 659",
        "tel": "+79312261080",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 575,
        "name": "Принцесса Фике",
        "address": "192174, Санкт-Петербург г, пр-кт Александровской Фермы, д. 8",
        "tel": "+79319809545",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 576,
        "name": "Прокофьева Маргарита (вывеска Этика)",
        "address": "193079, Санкт-Петербург г, ул Народная, д. 1",
        "tel": "89052092552",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 577,
        "name": "Пронина Светлана (Караваевская) ОПТ",
        "address": "192177, Город Санкт-Петербург, ул Караваевская, д. 28, к. 1, литера А, кв. 114",
        "tel": "89021675869",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 578,
        "name": "Птичкина Елена (Караваевская) ОПТ (отзвон за час)",
        "address": "192177, Санкт-Петербург г, вн.тер.г. Рыбацкое, ул Караваевская, 23",
        "tel": "89216583861",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 579,
        "name": "Рахматов (Караваевская 24)",
        "address": "192177, Санкт-Петербург г, ул Караваевская, д. 24",
        "tel": "+79697172323",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 580,
        "name": "Римэйкерс ООО ОПТ (Советский)",
        "address": "192076, Санкт-Петербург г, тер. Усть-Славянка, пр-кт Советский, д. 43, к. 1",
        "tel": "+79219492352",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 581,
        "name": "Румянцева Ирина",
        "address": "Санкт-Петербург г, ул Ольги Берггольц, д. 24, кв. 26",
        "tel": "+79119873873",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 582,
        "name": "Рыжикова Юлия",
        "address": "192076, Санкт-Петербург г, вн.тер.г. муниципальный округ Рыбацкое, пр-кт Рыбацкий, д. 29, к. 1, литера А",
        "tel": "89217979988",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 583,
        "name": "Сабрина Ася (Караваевская 24)",
        "address": "192177, Санкт-Петербург г, ул Караваевская, д. 24, к. 1, литера А, вход под аптека озерки",
        "tel": "+79516858581",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 584,
        "name": "Сафарян",
        "address": "192076, Санкт-Петербург г, пр-кт Шлиссельбургский, д. 6, литера А",
        "tel": "+79046368364",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 585,
        "name": "Сашина Наталья Вадимовна (Общественный пер.салон Иль Де лис) ОПТ",
        "address": "192029, Санкт-Петербург г, вн.тер.г. муниципальный округ Невская застава, пер Общественный, д. 5",
        "tel": "+79219388879",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 586,
        "name": "Светлаков С.С. (Елизарова, вывеска Чио)",
        "address": "192148, Санкт-Петербург г, вн.тер.г. Невская застава, пр-кт Елизарова, 23",
        "tel": "+79817994469",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 587,
        "name": "Светлана (Жемчуг) ОПТ",
        "address": "193079, Санкт-Петербург г, Народная ул, дом № 11, корпус 2",
        "tel": "+79219843373",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 588,
        "name": "Свиридова Екатерина (Русановская)",
        "address": "193149, Санкт-Петербург г, ул Русановская, д. 18, к. 1, кв. 120, этаж 18",
        "tel": "+79040909037",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 589,
        "name": "Секацкая Светлана",
        "address": "192076, Санкт-Петербург г, пр-кт Шлиссельбургский, д. 18, к. 1, литера А, кв. 312, парадная 6",
        "tel": "+79119960358",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 590,
        "name": "Семейная парикмахерская (Рабфаковский)",
        "address": "192012, Санкт-Петербург г, пер 2-й Рабфаковский, д. 5, вход через Озон",
        "tel": "+79992371466",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 591,
        "name": "Сироткина Анастасия",
        "address": "192177, Санкт-Петербург г, ул Караваевская, д. 32, к. 1, литера А, кв. 8",
        "tel": "+79216413714",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 592,
        "name": "Слава (Седова 35, вывеска Барбер)",
        "address": "192148, Санкт-Петербург г, ул Седова, 35",
        "tel": "+79522810011",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 593,
        "name": "Смирнова Ольга (студия БС)",
        "address": "192174, Санкт-Петербург г, пр-кт Александровской Фермы, д. 8, ЖК Грин сити",
        "tel": "+79112875887",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 594,
        "name": "Сорокин Василий Сергеевич  (Ново-Александровская)",
        "address": "192012, Санкт-Петербург г, ул Ново-Александровская, д. 14, литера А",
        "tel": "+79602601166",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 595,
        "name": "Соседка (Металлострой)",
        "address": "Санкт-Петербург г, д. 11, вн.тер.г. поселок Металлострой, ул Центральная",
        "tel": "+79117533335",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 596,
        "name": "София (Металлострой, Садовая 6)",
        "address": "196641, Санкт-Петербург г, п Металлострой, ул Садовая, д. 6, вход там, где WB",
        "tel": "+79522701771",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 597,
        "name": "Стрижка (Скачков пер.)",
        "address": "192177, Санкт-Петербург г, пер Скачков, д. 5",
        "tel": "89650504142",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 598,
        "name": "Студия красоты \"25 квадратов\"",
        "address": "192177, Санкт-Петербург г, ул Караваевская, д. 8, кв. 175",
        "tel": "+79062482042",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 599,
        "name": "Суванова Юлдуз ЧМ",
        "address": "192029, Санкт-Петербург г, ул Бабушкина, д. 14, кв. 26",
        "tel": "89534101864",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 600,
        "name": "Тиара",
        "address": "193149, Санкт-Петербург г, вн.тер.г. муниципальный округ Народный, ул Русановская, д. 17, к. 1, литера А",
        "tel": "+79219944005",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 601,
        "name": "Тулаганова Саида",
        "address": "192171, Санкт-Петербург г, ул Бабушкина, д. 55, к. 1, кв. 245",
        "tel": "+79312285899",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 602,
        "name": "Туча О.В.",
        "address": "193079, Санкт-Петербург г, наб Октябрьская, д. 90, к. 5, литера Е",
        "tel": "+79117838112",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 603,
        "name": "Тэсс салон ( Ивановская 7)",
        "address": "192171, Санкт-Петербург г, ул Ивановская, д. 7, салон красоты Тесс",
        "tel": "+79522424624",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 604,
        "name": "Усинкова Ульяна (Лиана, Советский)",
        "address": "192076, Санкт-Петербург г, тер. Усть-Славянка, пр-кт Советский, д. 20",
        "tel": "+79522361721",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 605,
        "name": "Фабрика красоты",
        "address": "192029, Санкт-Петербург г, пр-кт Обуховской Обороны, д. 119б, литера Б",
        "tel": "+79219392652",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 606,
        "name": "Фомичева Ирина",
        "address": "193149, Санкт-Петербург г, вн.тер.г. Народный, ул Русановская, д. 19, к. 3, кв. 416",
        "tel": "+79111481317",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 607,
        "name": "Фри Стайл (Ивановская) ОПТ",
        "address": "192171, Санкт-Петербург г, Ивановская ул, дом № 13",
        "tel": "89523570111",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 608,
        "name": "Хлебникова(Народная))",
        "address": "193315, Санкт-Петербург г, вн.тер.г. Народный, ул Народная, 45",
        "tel": "+79219526501",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 609,
        "name": "Черкашина С.В. (вывеска комплекс Атлант)",
        "address": "192177, Санкт-Петербург г, пр-кт Обуховской Обороны, д. 301, литера А",
        "tel": "+79213929858",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 610,
        "name": "Чулок-завиток",
        "address": "192012, Санкт-Петербург г, ул Бабушкина, д. 131, к. 2, литера А",
        "tel": "+79219944005",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 611,
        "name": "Шаева Маргарита",
        "address": "193149, Санкт-Петербург г, Русановская ул, дом 16, корпус 3, строение 1, кв. 735",
        "tel": "89045541175",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 612,
        "name": "Шанель (вывеска На Ногина) ОПТ",
        "address": "192029, Санкт-Петербург г, вн.тер.г. Невская застава, пер Ногина, 4",
        "tel": "+79643759091",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 613,
        "name": "Шараева Екатерина (Орион) С 11 Ч.",
        "address": "192012, Санкт-Петербург г, ул Бабушкина, д. 82, к. 3",
        "tel": "+79216414044",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 614,
        "name": "Шелестенко Александр",
        "address": "192076, Санкт-Петербург г, вн.тер.г. муниципальный округ Рыбацкое, пр-кт Рыбацкий, д. 57, к. 1, литера Б, кв. 99",
        "tel": "+79214508621",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 615,
        "name": "Шик (Металлострой)",
        "address": "196641, Санкт-Петербург г, вн.тер.г. поселок Металлострой, п Металлострой, ул Школьная, 3",
        "tel": "+79119051632",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 616,
        "name": "Ширинов Эльшад (Народная 5) ОПТ",
        "address": "193079, Санкт-Петербург г, Народная ул, дом № 5",
        "tel": "89522404253",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 617,
        "name": "Ширинов Эльшад (Народная 87)",
        "address": "193315, Санкт-Петербург г, ул Народная, д. 87",
        "tel": "+79657578940",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 618,
        "name": "Шкиренко Ю.В.",
        "address": "192177, Санкт-Петербург г, Тепловозная (Рыбацкое) ул, дом № 31",
        "tel": "89219693905",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 619,
        "name": "Шусть Е.М.",
        "address": "193079, Санкт-Петербург г, ул Народная, д. 21",
        "tel": "+79216352596",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 620,
        "name": "Щеголева Анна (Рабфаковский )",
        "address": "192012, Санкт-Петербург г, пер 2-й Рабфаковский, д. 17, к. 1, литера А, кв. 1",
        "tel": "+79116448160",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 621,
        "name": "Экспресс (Елизарова)",
        "address": "192148, Санкт-Петербург г, пр-кт Елизарова, д. 25",
        "tel": "89050732291",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 622,
        "name": "Экспресс (Ивановская 25)",
        "address": "192171, Город Санкт-Петербург, ул Ивановская, д. 25, литера А",
        "tel": "+79050732291",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 623,
        "name": "Экспресс (Крупская)",
        "address": "192029, Город Санкт-Петербург, ул Крупской, д. 4, литера А",
        "tel": "+79050732291",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 624,
        "name": "Элит (Сидорова Е.В.)",
        "address": "192012, Санкт-Петербург г, ул Бабушкина, д. 82, к. 3, стр. 1",
        "tel": "89111750155",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 625,
        "name": "Эстет",
        "address": "192131, Санкт-Петербург г, вн.тер.г. муниципальный округ Обуховский, ул Шелгунова, д. 7, к. 1, литера А",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 626,
        "name": "Юдина Наталья",
        "address": "196643, Санкт-Петербург г, п Понтонный, ул Заводская, д. 2, литера А",
        "tel": "+79522262321",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 627,
        "name": "Юдов П.Ю. (Шлиссельбургский) ОПТ",
        "address": "192177, Санкт-Петербург г, вн.тер.г. Рыбацкое, пр-кт Шлиссельбургский, 37, кв. 54",
        "tel": "+79817172415",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 628,
        "name": "Явлаш Олеся",
        "address": "192177, Санкт-Петербург г, ул Караваевская, д. 32, к. 2, Лидер",
        "tel": "89217716777",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 629,
        "name": "Ямпольская Татьяна",
        "address": "192174, Санкт-Петербург г, ул Бабушкина, д. 70, литера Е, кв. 18",
        "tel": "+79062502502",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 630,
        "name": "Ястреб Инна",
        "address": "193315, Санкт-Петербург г, вн.тер.г. муниципальный округ Народный, ул Народная, д. 90, литера З, кв. 42",
        "tel": "+79119390143",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 631,
        "name": "ЯЯЯБарбер Генко ЗАКРЫТО",
        "address": "Санкт-Петербург г, 18 Ул. Парфеновская,.д. 9, к. 1, стр. 1 парадная",
        "tel": "89602345749",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 632,
        "name": "ЯЯЯБурум (Арам, Лиана) ЗАКРЫТО",
        "address": "196641, Санкт-Петербург г, вн.тер.г. муниципальный округ Владимирский округ, ул Социалистическая, д. 22, к. 4",
        "tel": "+79117770233",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    },
    {
        "id": 633,
        "name": "ЯЯЯТатьяна (Ткачей 46)",
        "address": "192029, Санкт-Петербург г, ул Ткачей, д. 46, литера ЕД, кв. 45",
        "tel": "+79118126705",
        "LPR": null,
        "servicePROF": null,
        "paint": null,
        "washingRoom": null,
        "reception": null,
        "comments": null,
        "masterBD": null,
        "salonBD": null
    }
]

